stages:
  - maventry

maven-build: #this is a job
  stage: maventry
  tags:
    - springboot_tag #this is the link to the shell runner on the server
  script:
    - pwd
    - echo "This commands executes properly" >> /home/miguelm1/delete.txt