package com.example.cryptoshop_backend.controllers;

import com.example.cryptoshop_backend.models.User;
import com.example.cryptoshop_backend.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

public class UserController {
    @Controller
    public static class MainController {
        @Autowired // This means to get the bean called userRepository
        // Which is auto-generated by Spring, we will use it to handle the data
        private UserRepository userRepository;

        @PostMapping(path="/addUser") // Map ONLY POST Requests
        public @ResponseBody String addNewUser (@RequestParam String name
                , @RequestParam String email, @RequestParam String username
                , @RequestParam String hashed_pass)
        {
            // @ResponseBody means the returned String is the response, not a view name
            // @RequestParam means it is a parameter from the GET or POST request

            User n = new User();
            n.setName(name);
            n.setEmail(email);
            n.setUsername(username);
            n.setHashed_pass(hashed_pass);
            userRepository.save(n);
            return "Saved\n";
        }

        @GetMapping(path="/allUsers")
        public @ResponseBody Iterable<User> getAllUsers() {
            // This returns a JSON or XML with the users
            return userRepository.findAll();
        }

        @GetMapping("/test")
        public ResponseEntity<String> testGET () {
            return ResponseEntity.status(HttpStatus.OK).body("Everything good");
        }
    }
}
